spring:
  # Development Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/pdms_dev?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    
  # Elasticsearch Configuration
  elasticsearch:
    uris: http://localhost:9200
    
# Storage Configuration for Development
storage:
  location: storage/dev

# Logging Configuration for Development
logging:
  level:
    com.vtnet.pdms: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG 