spring:
  profiles:
    active: dev
  application:
    name: pdms

  # Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    
  # File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:default_dev_secret_key_which_should_be_changed_in_production}
    expiration: 1800000  # 30 minutes in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds

# Storage Configuration
storage:
  location: ${STORAGE_LOCATION:storage}

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging Configuration
logging:
  level:
    root: INFO
    com.vtnet.pdms: INFO
    org.springframework.web: INFO
    org.hibernate: INFO 